### ISSUE TITLE
Hotel Dusk - Touch screen issue

### ISSUE THREAD

**Issue by DarthVitrial** [DS-Homebrew/nds-bootstrap#708]
Tell us which console you are using:

New 3DS xl, latest system firmware.

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:
Luma3ds 10.0.1

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x]  Nightly _[insert here commit hash]_

Nightly f8da9b8

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

SD Card

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

Hotel dusk:
Room  215

The issues:

I’ve noticed two issues with the game.
First (https://github.com/DS-Homebrew/nds-bootstrap/issues/231) an odd sort of graphical flicker where an image from the top screen will appear on the bottom screen for a split second, or vice versa. You can observe this just by launching the game and watching through the intro cinematic, or by entering a conversation with an npc and just waiting a bit. 

The second issue is one with the touchscreen - the game reads your stylus as being about a half an inch below where it actually is. This is easy to reproduce if you just take out the in game notebook and try to write on it.

Neither is game breaking, but they are a bit inconvenient.

**Comment by RocketRobz** [comment]
Weird. Haven't heard anyone else with the touchscreen issue.
Can anyone else confirm this?

**Comment by DarthVitrial** [comment]
The weirdest thing is the touchscreen issue isn’t 100% reproducible for me either. 
after about 15-20 minutes of play it started working more accurately (still a bit off center).

**Comment by Kastakin** [comment]
Flickering for me was gone launching in NTR mode (forcing the CPU frequency).
I haven't noticed any issue with the touchscreen though...

**Comment by limmynade** [comment]
I've played and finished the sequel of Hotel Dusk but i don't remember any problems like those, it used to crash randomly but that was fixed in a update.

**Comment by kaosjr** [comment]
Tested, the graphical issues are only present if you use TWL speeds (on both 3DS and DSi). If set to NTR speeds, the graphical issues vanish. Here's a video of the aforementioned graphical issues: [](https://youtu.be/VgBecD1aDVg)
I didn't personally notice any touchscreen problems.

**Comment by kaosjr** [comment]
As well, the PAL version of the game appears to have the same flickering issues under TWL speeds, so this problem appears to affect all regional releases, not just the USA release.

**Comment by hansoljin** [comment]
Flickering is still present on the latest nightly as of this writing. NTR speed does fix it, as mentioned.
Can't seem to replicate that touchscreen thing anywhere.

**Comment by RocketRobz** [comment]
Closing, as there have been no recent reports about this.
