### ISSUE TITLE
Removing any type of Slot-1 card (DS, 3DS game carts) in sleep mode resets console

### ISSUE THREAD

**Issue by FateForWindows** [DS-Homebrew/nds-bootstrap#79]
If a game is being ran, the console is put into sleep mode and a slot-1 card of any type (referencing actual game carts, not flashcards as that's different from this), the 3DS will reset as if you removed a DS card while playing the game from the cartridge. This does not affect when the console is out of sleep mode and the card is removed.

**Comment by Robz8** [comment]
That's been known for a while, but thanks for opening this issue anyways.
It should be fixed in the future.

**Comment by Stack3r** [comment]
Does this issue still happen?

**Comment by Robz8** [comment]
Yes.

**Comment by Stack3r** [comment]
Is this issue still present? If it is then the force sleep patch should fix this right?

**Comment by dogresidue24** [comment]
This issue still exists and it ruins Pokemon Black for me since I need IR access but I don't want to risk powering off my DSi by bumping my IR-compatible game cartridge.

**Comment by Kaisaan** [comment]
Issue seems to still occur. Tested with Super Mario 64 DS USA (Rev 1) in Slot-1, and tried games such as Sonic Rush and Mario & Luigi: Bowser's inside Story. Setting my console to sleep mode and taking out the cartridge works fine, both games still run normally and my console is still on. Trying SM64 DS through nds-bootstrap and my system turns off when I eject the cartridge. It seems that running the same game as the one inserted in Slot-1 still causes the console to turn off.  Tested on my DSi XL with Twilightmenu version 13.1.0 and nds-bootstrap version 0.32.1

**Comment by Meowlithius** [comment]
Still is occurring in 2020. My this issue is lasting isn't it? (Well I guess it's on a back burner and not super important) On my New 3ds XL this issue occurs. I think because of the way ndsbootstrap handles game titles, even dumped ROMs are "ejected" from the system. And no code or way has been made to prevent "ejection" especially if it's a local dumped ROM. If it's a physical DS cart it makes sense to eject to the home menu, just not local Dumps.

**Comment by RocketRobz** [comment]
Finally fixed in d896e305 (though this still happens in DS games that use IR)
